create table if not exists public.response_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text not null,
  question_id text not null,
  answer text not null,
  answers jsonb not null default '{}'::jsonb,
  exact_moment text
);

alter table public.response_events enable row level security;

drop policy if exists "Anyone can submit response events" on public.response_events;
create policy "Anyone can submit response events"
  on public.response_events
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Signed-in developers can read response events" on public.response_events;
create policy "Signed-in developers can read response events"
  on public.response_events
  for select
  to authenticated
  using (true);